declare module '@editorjs/link';
declare module '@editorjs/header';
declare module '@editorjs/list';
declare module '@editorjs/quote';
declare module '@editorjs/image';
declare module '@editorjs/embed';
declare module "@editorjs/raw"
declare module "@editorjs/simple-image"
declare module "@editorjs/checklist"
declare module "@coolbytes/editorjs-delimiter"
declare module "editorjs-alert"
declare module "editorjs-toggle-block"
declare module "@alkhipce/editorjs-aitext"
declare module "@editorjs/attaches"
declare module "sortablejs"
declare module "editorjs-mermaid"
declare module "editorjs-telegram-post"
declare module "editorjs-audio-player"
declare module "@sotaproject/strikethrough"
declare module "@editorjs/marker"
declare module "editorjs-annotation"
declare module "editorjs-inline-hotkey"
declare module "editorjs-mention-tool"
declare module "editorjs-inline-image"
declare module "@calumk/editorjs-nested-checklist"
declare module "@editorjs/text-variant-tune"
declare module "editorjs-googlemap"
