import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// @ts-ignore
import "./globals.css";
import { ThemeProvider } from "@/components/generals/theme/theme-provider";
import Footer from "@/components/generals/footer/footer";
import { TooltipProvider } from "@/components/ui/tooltip";
import { SocialBar } from "@/components/generals/social-bar";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { dark, neobrutalism } from '@clerk/themes'
import HeaderSection from "@/components/generals/header";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
    //  appearance={{
    //           // baseTheme: [dark],

    //     // baseTheme: dark,
    //   }}
    >

    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
         <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
            >
            <TooltipProvider>
              {/* <SocialBar/> */}
              <HeaderSection/>

            {children}
            <Footer/>
            </TooltipProvider>
          </ThemeProvider>
      </body>
    </html>
            </ClerkProvider>
  );
}
